export const CREATETASK_REQUEST ="CREATETASK_REQUEST";
export const CREATETASK_SUCCESS ="CREATETASK_SUCCESS";
export const CREATETASK_FAILURE ="CREATETASK_REQUEST";


export const GETTASK_REQUEST ="GETTASK_REQUEST";
export const GETTASK_SUCCESS ="GETTASK_SUCCESS";
export const GETTASK_FAILURE ="GETTASK_REQUEST";