export const CREATETASK_REQUEST ="CREATETASK_REQUEST";
export const CREATETASK_SUCCESS ="CREATETASK_SUCCESS";
export const CREATETASK_FAILURE ="CREATETASK_REQUEST";


export const GETTASK_REQUEST ="GETTASK_REQUEST";
export const GETTASK_SUCCESS ="GETTASK_SUCCESS";
export const GETTASK_FAILURE ="GETTASK_REQUEST";




export const GETPROJECT_REQUEST ="GETPROJECT_REQUEST";
export const GETPROJECT_SUCCESS ="GETPROJECT_SUCCESS";
export const GETPROJECT_FAILURE ="GETTASK_REQUEST";

export const EDITTASK_REQUEST="EDITTASK_REQUEST";
export const EDITTASK_SUCCESS="EDITTASK_SUCCESS";
export const EDITTASK_FAILURE="EDITTASK_FAILURE";


export const DELETETASK_REQUEST = "DELETETASK_REQUEST"
export const DELETETASK_REQUEST = "DELETETASK_REQUEST"
export const DELETETASK_REQUEST = "DELETETASK_REQUEST"