export const ADD_EXPENSE="ADD_EXPENSE";
export const EDIT_EXPENSE="EDIT_EXPENSE";
export const DELETE_EXPENSE="DELETE_EXPENSE";
export const EDIT_POP="EDIT_POP";
export const UPLOAD_REQUEST="UPLOAD_REQUEST";
export const UPLOAD_FAILURE="UPLOAD_FAILURE";
export const UPLOAD_SUCCESS="UPLOAD_SUCCESS";
